In [1]:
#Links utiles
#https://towardsdatascience.com/data-preprocessing-with-python-pandas-part-1-missing-data-45e76b781993
#https://towardsdatascience.com/7-different-ways-to-filter-pandas-dataframes-9e139888382a
#https://www.analyticslane.com/2020/01/13/filtrado-de-cadenas-de-texto-en-dataframe-con-pandas/
#https://www.analyticslane.com/2019/03/25/como-eliminar-columnas-y-filas-en-un-dataframe-pandas/

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model, model_selection

df = pd.read_csv("datosfiltrados.csv", sep=",",index_col=False)

df.head()

,ix,Id,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,id_anony
0,135020,503,2017,1,13008,CALCULO 2,ELE-PLS13,2,1,2017,1,N,0,7,0,0,0,0,NaN,es_1444
1,135021,504,2017,1,13008,CALCULO 2,CGF-PLS13,2,1,2017,1,N,0,5,0,0,0,0,NaN,es_4238
2,135022,505,2017,1,13008,CALCULO 2,ELE-PLS13,2,1,2017,1,S,2016,0,0,0,0,0,"1F-1,2F-2",es_4245
3,135023,506,2017,1,13008,CALCULO 2,CIV-PLS13,2,1,2017,1,N,0,0,0,0,0,0,NaN,es_4967
4,135024,507,2017,1,13008,CALCULO 2,CGF-PLS13,2,1,2017,1,S,2017,21,10,0,0,0,3F-C-3,es_414

In [3]:
#Con este comando busco los datos no disponibles
df.isna().sum()

ix                 0
Id                 0
danho              0
ciclo              0
Cod.Asign          0
Asignatura         0
Cod.Car.Sec        0
Cod.Curso          0
Convocatoria       0
Anho               0
Semestre           0
Aprobado           0
Anho.Firma         0
Primer.Par         0
Segundo.Par        0
AOT                0
Primer.Rec         0
Segundo.Rec        0
Nota.Final      8641
id_anony           0
dtype: int64

In [4]:
#Con esta funcion determino el porcentaje de datos no disponible
df.isna().sum()/len(df)*100

ix               0.000000
Id               0.000000
danho            0.000000
ciclo            0.000000
Cod.Asign        0.000000
Asignatura       0.000000
Cod.Car.Sec      0.000000
Cod.Curso        0.000000
Convocatoria     0.000000
Anho             0.000000
Semestre         0.000000
Aprobado         0.000000
Anho.Firma       0.000000
Primer.Par       0.000000
Segundo.Par      0.000000
AOT              0.000000
Primer.Rec       0.000000
Segundo.Rec      0.000000
Nota.Final      48.855091
id_anony         0.000000
dtype: float64

In [5]:
#Con esta funcion, creo un dataframe que incluya exclusivamente a los alumnos que cursan probabilidad y estadistica
proba=df[df.Asignatura=='PROBABILIDAD Y ESTADISTICA']

dimensiones=proba.shape

Index=np.zeros(dimensiones[0])
for i in range(len(Index)): 
    Index[i]=i

proba.insert(0,"Indice",Index,True)
list(proba.columns)
proba.head(10)

#proba=proba.drop(...)

,Indice,ix,Id,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,...,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,id_anony
3904,0.0,150230,4185,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CIV-PLS13,3,1,...,2,N,0,2,0,0,0,0,NaN,es_7719
3905,1.0,150231,4186,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CGF-PLS13,3,1,...,2,N,0,4,0,0,0,0,NaN,es_1972
3906,2.0,150232,4187,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CIV-PLS13,3,1,...,2,N,0,0,0,0,0,0,3F-1,es_2129
3907,3.0,150233,4188,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CIV-PLS13,3,1,...,2,N,0,0,0,0,0,0,NaN,es_2803
3908,4.0,150234,4189,2017,2,13014,PROBABILIDAD Y ESTADISTICA,ELE-PLS13,3,1,...,2,N,2016,0,0,0,0,0,2F-1,es_2441
3909,5.0,150235,4190,2017,2,13014,PROBABILIDAD Y ESTADISTICA,ECA-PLS13,3,1,...,2,S,2017,5,28,0,34,42,3F-4,es_2712
3910,6.0,150236,4191,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CIV-PLS13,3,1,...,2,N,0,12,0,0,0,0,NaN,es_3559
3911,7.0,150237,4192,2017,2,13014,PROBABILIDAD Y ESTADISTICA,ELE-PLS13,3,1,...,2,S,2016,3,0,0,0,0,"2F-1,3F-4",es_3612
3912,8.0,150238,4193,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CGF-PLS13,3,1,...,2,N,0,0,23,0,12,15,NaN,es_2773
3913,9.0,150239,4194,2017,2,13014,PROBABILIDAD Y ESTADISTICA,CIV-PLS13,3,1,...,2,N,0,8,0,0,0,0,NaN,es_7257

In [6]:
#Con esta funcion, recorto las columnas que no necesito utilizar

proba=proba.drop(['Semestre','ix','Id','Asignatura','Cod.Asign'],axis=1)

In [7]:
proba

,Indice,danho,ciclo,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,id_anony
3904,0.0,2017,2,CIV-PLS13,3,1,2017,N,0,2,0,0,0,0,NaN,es_7719
3905,1.0,2017,2,CGF-PLS13,3,1,2017,N,0,4,0,0,0,0,NaN,es_1972
3906,2.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,3F-1,es_2129
3907,3.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,NaN,es_2803
3908,4.0,2017,2,ELE-PLS13,3,1,2017,N,2016,0,0,0,0,0,2F-1,es_2441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,2019,2,CIV-PLS13,3,2,2019,N,0,0,7,4,0,0,NaN,es_7097
17101,1547.0,2019,2,CIV-PLS13,3,2,2019,N,0,4,0,0,0,0,NaN,es_7099
17102,1548.0,2019,2,CIV-PLS13,3,2,2019,N,0,7,12,3,8,0,NaN,es_7250
17103,1549.0,2019,2,CIV-PLS13,3,2,2019,S,2019,24,28,10,0,0,1F-5,es_9820
17104,1550.0,2019,2,CIV-PLS13,3,2,2019,N,2019,16,15,9,26,0,NaN,es_7251

In [8]:
#Esta bandera contiene a todos los que tienen NaN en sus casillas
flagNA=proba["Nota.Final"].isna()

#Esta bandera contiene a todos los que NO tienen NaN en sus casillas
flagNotNA=np.logical_not(flagNA)

#Aqui se asigna la columna donde se define si paso o no el alumno, por defecto, nadie paso
#proba["Paso"]=False <-Esto recomendo el profesor, pero por alguna razon no funciono, y tuve que optar por lo que esta abajo
proba.assign(Aprobo = False)

#dataframe.localizar[]
proba.loc[flagNotNA,"Aprobo"]=proba["Nota.Final"][flagNotNA].str.split(',').str[-1].str.split('-').str[-1].astype('int')>=2


#Aqui volvemos a llamar al dataframe para verificar los cambios
proba

#flagNA=lectura["Nota.Final"].isna()
#flagNotNA=np.logical_not(flagNA)
#lectura["Paso"]=False
#lectura.loc[flagNotNA,"Paso"]=lectura["Nota.Final"][flagNotNA].str.split(',').str[-1].str.split('-').str[-1].astype('int')>=2

,Indice,danho,ciclo,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,id_anony,Aprobo
3904,0.0,2017,2,CIV-PLS13,3,1,2017,N,0,2,0,0,0,0,NaN,es_7719,NaN
3905,1.0,2017,2,CGF-PLS13,3,1,2017,N,0,4,0,0,0,0,NaN,es_1972,NaN
3906,2.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,3F-1,es_2129,False
3907,3.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,NaN,es_2803,NaN
3908,4.0,2017,2,ELE-PLS13,3,1,2017,N,2016,0,0,0,0,0,2F-1,es_2441,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,2019,2,CIV-PLS13,3,2,2019,N,0,0,7,4,0,0,NaN,es_7097,NaN
17101,1547.0,2019,2,CIV-PLS13,3,2,2019,N,0,4,0,0,0,0,NaN,es_7099,NaN
17102,1548.0,2019,2,CIV-PLS13,3,2,2019,N,0,7,12,3,8,0,NaN,es_7250,NaN
17103,1549.0,2019,2,CIV-PLS13,3,2,2019,S,2019,24,28,10,0,0,1F-5,es_9820,True
17104,1550.0,2019,2,CIV-PLS13,3,2,2019,N,2019,16,15,9,26,0,NaN,es_7251,NaN

In [9]:
#Aqui creo una columna en donde se asigna con que puntaje paso
proba.assign(Calificacion = 0)

#Aqui renombro algunas columnas para tener algo en un formato mas facil de comprender
proba.rename(columns={'AOT': 'Taller','Primer.Par' : '1P','Segundo.Par':'2P'},inplace = True)

#Esta linea de codigo asigna la nota final de cada alumno de la catedra
proba.loc[flagNotNA,"Calificacion"]=proba["Nota.Final"][flagNotNA].str.split(',').str[-1].str.split('-').str[-1].astype('int')
display(proba)

,Indice,danho,ciclo,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Aprobado,Anho.Firma,1P,2P,Taller,Primer.Rec,Segundo.Rec,Nota.Final,id_anony,Aprobo,Calificacion
3904,0.0,2017,2,CIV-PLS13,3,1,2017,N,0,2,0,0,0,0,NaN,es_7719,NaN,NaN
3905,1.0,2017,2,CGF-PLS13,3,1,2017,N,0,4,0,0,0,0,NaN,es_1972,NaN,NaN
3906,2.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,3F-1,es_2129,False,1.0
3907,3.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,NaN,es_2803,NaN,NaN
3908,4.0,2017,2,ELE-PLS13,3,1,2017,N,2016,0,0,0,0,0,2F-1,es_2441,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,2019,2,CIV-PLS13,3,2,2019,N,0,0,7,4,0,0,NaN,es_7097,NaN,NaN
17101,1547.0,2019,2,CIV-PLS13,3,2,2019,N,0,4,0,0,0,0,NaN,es_7099,NaN,NaN
17102,1548.0,2019,2,CIV-PLS13,3,2,2019,N,0,7,12,3,8,0,NaN,es_7250,NaN,NaN
17103,1549.0,2019,2,CIV-PLS13,3,2,2019,S,2019,24,28,10,0,0,1F-5,es_9820,True,5.0
17104,1550.0,2019,2,CIV-PLS13,3,2,2019,N,2019,16,15,9,26,0,NaN,es_7251,NaN,NaN

In [10]:
#Aqui encuentro la firma del alumno y asigno las respuestas a una columna
firma=proba["1P"]+proba["2P"]+proba["Taller"]
proba.insert(11,"Firma",firma)
display(proba)

,Indice,danho,ciclo,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Aprobado,Anho.Firma,1P,2P,Firma,Taller,Primer.Rec,Segundo.Rec,Nota.Final,id_anony,Aprobo,Calificacion
3904,0.0,2017,2,CIV-PLS13,3,1,2017,N,0,2,0,2,0,0,0,NaN,es_7719,NaN,NaN
3905,1.0,2017,2,CGF-PLS13,3,1,2017,N,0,4,0,4,0,0,0,NaN,es_1972,NaN,NaN
3906,2.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,0,3F-1,es_2129,False,1.0
3907,3.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,0,0,0,0,0,NaN,es_2803,NaN,NaN
3908,4.0,2017,2,ELE-PLS13,3,1,2017,N,2016,0,0,0,0,0,0,2F-1,es_2441,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,2019,2,CIV-PLS13,3,2,2019,N,0,0,7,11,4,0,0,NaN,es_7097,NaN,NaN
17101,1547.0,2019,2,CIV-PLS13,3,2,2019,N,0,4,0,4,0,0,0,NaN,es_7099,NaN,NaN
17102,1548.0,2019,2,CIV-PLS13,3,2,2019,N,0,7,12,22,3,8,0,NaN,es_7250,NaN,NaN
17103,1549.0,2019,2,CIV-PLS13,3,2,2019,S,2019,24,28,62,10,0,0,1F-5,es_9820,True,5.0
17104,1550.0,2019,2,CIV-PLS13,3,2,2019,N,2019,16,15,40,9,26,0,NaN,es_7251,NaN,NaN

In [11]:
#Aqui verifico si el alumno cumple con los requisitos para rendir examen final (firma>=35 y taller>=6) y/o examen recuperatorio.. 
#... (firma>=15) y lo almaceno en vectores booleanos
Requisito15=proba["Firma"]>=15
Requisito35=proba["Firma"]>=35
RequisitoT=proba["Taller"]>=6

DerechoFinal=np.logical_and(Requisito35,RequisitoT)
DerechoRecu=Requisito15 & RequisitoT
#display(Requisito35)
#display(RequisitoT)

display(DerechoFinal)
display(DerechoRecu)

proba.insert(13,"Derecho a Final",DerechoFinal)
proba.insert(13,"Derecho a Recuperatorio",DerechoRecu)

3904     False
3905     False
3906     False
3907     False
3908     False
         ...
17100    False
17101    False
17102    False
17103     True
17104     True
Length: 1551, dtype: bool

3904     False
3905     False
3906     False
3907     False
3908     False
         ...
17100    False
17101    False
17102    False
17103     True
17104     True
Length: 1551, dtype: bool

In [12]:
display(proba)

,Indice,danho,ciclo,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Aprobado,Anho.Firma,1P,...,Firma,Taller,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Nota.Final,id_anony,Aprobo,Calificacion
3904,0.0,2017,2,CIV-PLS13,3,1,2017,N,0,2,...,2,0,False,False,0,0,NaN,es_7719,NaN,NaN
3905,1.0,2017,2,CGF-PLS13,3,1,2017,N,0,4,...,4,0,False,False,0,0,NaN,es_1972,NaN,NaN
3906,2.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,...,0,0,False,False,0,0,3F-1,es_2129,False,1.0
3907,3.0,2017,2,CIV-PLS13,3,1,2017,N,0,0,...,0,0,False,False,0,0,NaN,es_2803,NaN,NaN
3908,4.0,2017,2,ELE-PLS13,3,1,2017,N,2016,0,...,0,0,False,False,0,0,2F-1,es_2441,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,2019,2,CIV-PLS13,3,2,2019,N,0,0,...,11,4,False,False,0,0,NaN,es_7097,NaN,NaN
17101,1547.0,2019,2,CIV-PLS13,3,2,2019,N,0,4,...,4,0,False,False,0,0,NaN,es_7099,NaN,NaN
17102,1548.0,2019,2,CIV-PLS13,3,2,2019,N,0,7,...,22,3,False,False,8,0,NaN,es_7250,NaN,NaN
17103,1549.0,2019,2,CIV-PLS13,3,2,2019,S,2019,24,...,62,10,True,True,0,0,1F-5,es_9820,True,5.0
17104,1550.0,2019,2,CIV-PLS13,3,2,2019,N,2019,16,...,40,9,True,True,26,0,NaN,es_7251,NaN,NaN

In [13]:
#Aqui retiro otras columnas que me parecian innecesarias para mi analisis
proba=proba.drop(['danho','ciclo','Cod.Curso','Convocatoria','Anho.Firma'],axis=1)

In [14]:
display(proba)

,Indice,Cod.Car.Sec,Anho,Aprobado,1P,2P,Firma,Taller,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Nota.Final,id_anony,Aprobo,Calificacion
3904,0.0,CIV-PLS13,2017,N,2,0,2,0,False,False,0,0,NaN,es_7719,NaN,NaN
3905,1.0,CGF-PLS13,2017,N,4,0,4,0,False,False,0,0,NaN,es_1972,NaN,NaN
3906,2.0,CIV-PLS13,2017,N,0,0,0,0,False,False,0,0,3F-1,es_2129,False,1.0
3907,3.0,CIV-PLS13,2017,N,0,0,0,0,False,False,0,0,NaN,es_2803,NaN,NaN
3908,4.0,ELE-PLS13,2017,N,0,0,0,0,False,False,0,0,2F-1,es_2441,False,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,CIV-PLS13,2019,N,0,7,11,4,False,False,0,0,NaN,es_7097,NaN,NaN
17101,1547.0,CIV-PLS13,2019,N,4,0,4,0,False,False,0,0,NaN,es_7099,NaN,NaN
17102,1548.0,CIV-PLS13,2019,N,7,12,22,3,False,False,8,0,NaN,es_7250,NaN,NaN
17103,1549.0,CIV-PLS13,2019,S,24,28,62,10,True,True,0,0,1F-5,es_9820,True,5.0
17104,1550.0,CIV-PLS13,2019,N,16,15,40,9,True,True,26,0,NaN,es_7251,NaN,NaN

In [15]:
Notas=proba["Nota.Final"]


Notas.head(10)

a=proba["Nota.Final"][flagNotNA]#.str.split(',').str[-1].str.split('-').str[-1].astype('int')
b=proba["Nota.Final"][flagNotNA].str.split(',')#.str[-1].str.split('-').str[-1].astype('int')
Aplazo1=proba["Nota.Final"][flagNotNA].str.split(',').str[0].str.split('-').str[-1].astype('int')
flag2=proba["Nota.Final"].str.split(',').str[1].isna()
notflag2=np.logical_not(flag2)
Aplazo2=proba["Nota.Final"][notflag2].str.split(',').str[1].str.split('-').str[-1].astype('int')
#e=proba["Nota.Final"][flagNotNA].str.split(',').str[2].str.split('-').str[-1].astype('int')


#display(np.size(flagNotNA))
#display(np.sum(flagNotNA))

#display(np.size(flag2))
#display(np.sum(flag2))


#display(a)
#display(b)
#display(Aplazo1)
#display(Aplazo2)
#display(e)

In [16]:

proba.insert(13,"Segundo Intento",Aplazo2)
proba.insert(13,"Primer Intento",Aplazo1)

In [17]:
#Aqui reordenamos las columnas para facilitar mas tarde la visualizacion y el uso de los datos de las mismas
proba=proba[["Indice","id_anony",'Anho',"Cod.Car.Sec","Nota.Final","Aprobado","1P","2P","Taller", "Firma" ,"Derecho a Recuperatorio","Derecho a Final","Primer.Rec","Segundo.Rec","Primer Intento","Segundo Intento","Calificacion","Aprobo"]]

In [18]:
display(proba)

,Indice,id_anony,Anho,Cod.Car.Sec,Nota.Final,Aprobado,1P,2P,Taller,Firma,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Primer Intento,Segundo Intento,Calificacion,Aprobo
3904,0.0,es_7719,2017,CIV-PLS13,NaN,N,2,0,0,2,False,False,0,0,NaN,NaN,NaN,NaN
3905,1.0,es_1972,2017,CGF-PLS13,NaN,N,4,0,0,4,False,False,0,0,NaN,NaN,NaN,NaN
3906,2.0,es_2129,2017,CIV-PLS13,3F-1,N,0,0,0,0,False,False,0,0,1.0,NaN,1.0,False
3907,3.0,es_2803,2017,CIV-PLS13,NaN,N,0,0,0,0,False,False,0,0,NaN,NaN,NaN,NaN
3908,4.0,es_2441,2017,ELE-PLS13,2F-1,N,0,0,0,0,False,False,0,0,1.0,NaN,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,es_7097,2019,CIV-PLS13,NaN,N,0,7,4,11,False,False,0,0,NaN,NaN,NaN,NaN
17101,1547.0,es_7099,2019,CIV-PLS13,NaN,N,4,0,0,4,False,False,0,0,NaN,NaN,NaN,NaN
17102,1548.0,es_7250,2019,CIV-PLS13,NaN,N,7,12,3,22,False,False,8,0,NaN,NaN,NaN,NaN
17103,1549.0,es_9820,2019,CIV-PLS13,1F-5,S,24,28,10,62,True,True,0,0,5.0,NaN,5.0,True
17104,1550.0,es_7251,2019,CIV-PLS13,NaN,N,16,15,9,40,True,True,26,0,NaN,NaN,NaN,NaN

In [19]:
#Finalmente reemplazaremos los espacios NaN de algunas columnas para facilitar el trabajo en otras librerias
values={'Aprobo':False,'Calificacion':0,'Primer Intento':0,'Segundo Intento':0}
proba.fillna(value=values,inplace=True)

In [20]:
display(proba)

,Indice,id_anony,Anho,Cod.Car.Sec,Nota.Final,Aprobado,1P,2P,Taller,Firma,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Primer Intento,Segundo Intento,Calificacion,Aprobo
3904,0.0,es_7719,2017,CIV-PLS13,NaN,N,2,0,0,2,False,False,0,0,0.0,0.0,0.0,False
3905,1.0,es_1972,2017,CGF-PLS13,NaN,N,4,0,0,4,False,False,0,0,0.0,0.0,0.0,False
3906,2.0,es_2129,2017,CIV-PLS13,3F-1,N,0,0,0,0,False,False,0,0,1.0,0.0,1.0,False
3907,3.0,es_2803,2017,CIV-PLS13,NaN,N,0,0,0,0,False,False,0,0,0.0,0.0,0.0,False
3908,4.0,es_2441,2017,ELE-PLS13,2F-1,N,0,0,0,0,False,False,0,0,1.0,0.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,es_7097,2019,CIV-PLS13,NaN,N,0,7,4,11,False,False,0,0,0.0,0.0,0.0,False
17101,1547.0,es_7099,2019,CIV-PLS13,NaN,N,4,0,0,4,False,False,0,0,0.0,0.0,0.0,False
17102,1548.0,es_7250,2019,CIV-PLS13,NaN,N,7,12,3,22,False,False,8,0,0.0,0.0,0.0,False
17103,1549.0,es_9820,2019,CIV-PLS13,1F-5,S,24,28,10,62,True,True,0,0,5.0,0.0,5.0,True
17104,1550.0,es_7251,2019,CIV-PLS13,NaN,N,16,15,9,40,True,True,26,0,0.0,0.0,0.0,False

In [21]:
proba.to_csv("Resumido.csv")

In [22]:
#Como los datos de los talleres esta mejor especificado en el anhno 2019, se creara un dataset que contenga los datos de ese anho en particular
probaTaller=proba[proba.Taller!=0]

In [23]:
display(probaTaller)

,Indice,id_anony,Anho,Cod.Car.Sec,Nota.Final,Aprobado,1P,2P,Taller,Firma,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Primer Intento,Segundo Intento,Calificacion,Aprobo
16795,1241.0,es_2441,2019,ELE-PLS13,NaN,N,14,18,5,37,False,False,0,0,0.0,0.0,0.0,False
16797,1243.0,es_9733,2019,ELE-PLS13,NaN,N,8,4,7,19,True,False,0,0,0.0,0.0,0.0,False
16798,1244.0,es_3106,2019,MEC-PLS13,NaN,N,9,11,7,27,True,False,14,0,0.0,0.0,0.0,False
16800,1246.0,es_9734,2019,ELE-PLS13,1F-5,S,22,35,8,65,True,True,0,0,5.0,0.0,5.0,True
16801,1247.0,es_3648,2019,IND-PLS13,1F-1,N,21,8,9,38,True,True,0,0,1.0,0.0,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17099,1545.0,es_9819,2019,ELE-PLS13,1F-4,S,21,23,10,54,True,True,0,0,4.0,0.0,4.0,True
17100,1546.0,es_7097,2019,CIV-PLS13,NaN,N,0,7,4,11,False,False,0,0,0.0,0.0,0.0,False
17102,1548.0,es_7250,2019,CIV-PLS13,NaN,N,7,12,3,22,False,False,8,0,0.0,0.0,0.0,False
17103,1549.0,es_9820,2019,CIV-PLS13,1F-5,S,24,28,10,62,True,True,0,0,5.0,0.0,5.0,True
17104,1550.0,es_7251,2019,CIV-PLS13,NaN,N,16,15,9,40,True,True,26,0,0.0,0.0,0.0,False

In [24]:
probaTaller.to_csv("ResumidoTaller.csv")

In [25]:
proba2019=proba[proba.Anho==2019]

In [26]:
display(proba2019)

,Indice,id_anony,Anho,Cod.Car.Sec,Nota.Final,Aprobado,1P,2P,Taller,Firma,Derecho a Recuperatorio,Derecho a Final,Primer.Rec,Segundo.Rec,Primer Intento,Segundo Intento,Calificacion,Aprobo
13418,1086.0,es_272,2019,MEC-PLS13,2F-1,N,8,16,0,24,False,False,36,0,1.0,0.0,1.0,False
13419,1087.0,es_273,2019,ELE-PLS13,NaN,N,0,0,0,0,False,False,0,0,0.0,0.0,0.0,False
13420,1088.0,es_8913,2019,ELE-PLS13,2F-1,N,9,20,0,29,False,False,26,0,1.0,0.0,1.0,False
13421,1089.0,es_3177,2019,CIV-PLS13,NaN,N,0,0,0,0,False,False,0,0,0.0,0.0,0.0,False
13422,1090.0,es_619,2019,CIV-PLS13,NaN,N,5,33,0,38,False,False,0,0,0.0,0.0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17100,1546.0,es_7097,2019,CIV-PLS13,NaN,N,0,7,4,11,False,False,0,0,0.0,0.0,0.0,False
17101,1547.0,es_7099,2019,CIV-PLS13,NaN,N,4,0,0,4,False,False,0,0,0.0,0.0,0.0,False
17102,1548.0,es_7250,2019,CIV-PLS13,NaN,N,7,12,3,22,False,False,8,0,0.0,0.0,0.0,False
17103,1549.0,es_9820,2019,CIV-PLS13,1F-5,S,24,28,10,62,True,True,0,0,5.0,0.0,5.0,True
17104,1550.0,es_7251,2019,CIV-PLS13,NaN,N,16,15,9,40,True,True,26,0,0.0,0.0,0.0,False

In [33]:
proba2019.to_csv("Resumido2019.csv")

In [28]:
#A partir de aqui inician codigos que no tienen nada que ver con el dataset genrado, pero fue de utilidad a la hora de crearlo
#No elimine estas lineas de codigo porque pense que podriuan ser utiles para otra aplicacion en el futuro

In [29]:
#Este comando fue utilizado para comprobar que tipo de datos recibe como dato la columna de notas finales
print(proba["Nota.Final"].tolist())
print([type(x) for x in proba["Nota.Final"].tolist()])

[type(x) for x in proba["Taller"].tolist()]

[nan, nan, '3F-1', nan, '2F-1', '3F-4', nan, '2F-1,3F-4', nan, nan, nan, '1F-3', nan, nan, nan, '2F-1,3F-2', '1F-2', '1F-5', nan, nan, nan, nan, nan, '2F-1,3F-2', '1F-2', nan, nan, nan, '3F-3', '1F-1,2F-3', '1F-1,2F-1', nan, '3F-3', '1F-1,2F-3', '1F-4', '3F-3', nan, '3F-2', nan, nan, nan, nan, '2F-5', '1F-3', nan, '1F-5', '3F-5', '1F-4', '1F-2', nan, '2F-1,3F-1', '1F-5', '1F-1,2F-1', nan, nan, '2F-2', nan, nan, nan, '1F-4', nan, '1F-4', nan, '3F-4', '2F-3', nan, nan, '2F-1,3F-3', '1F-3', '3F-2', '1F-1', nan, '2F-2', nan, '2F-1,3F-2', '3F-3', '2F-1,3F-3', '1F-1', '1F-3', '1F-2', '3F-5', '1F-4', '1F-3', nan, '1F-1,2F-1', '2F-5', '1F-1', '2F-4', nan, nan, nan, nan, nan, '2F-3', '3F-3', '1F-1', '1F-2', nan, '1F-4', '1F-2', nan, '1F-2', '1F-2', nan, nan, nan, '1F-5', nan, nan, nan, nan, nan, nan, nan, '1F-4', '2F-3', '2F-2', '1F-2', nan, '2F-1', '1F-5', '3F-3', '2F-4', '2F-5', '3F-4', '1F-1,3F-5', '3F-5', '1F-1,2F-3', '2F-1,3F-3', '1F-5', '3F-1', '2F-5', nan, nan, '1F-1,3F-3', nan, nan, nan, '3F-2', nan, nan, '3F-4', '1F-3', nan, '2F-3', nan, nan, nan, '1F-1,2F-1,3F-2', '1F-5', nan, '1F-5', '1F-5', '1F-5', '1F-5', '3F-2', nan, nan, nan, nan, '1F-4', '1F-3', '2F-2', nan, '2F-1,3F-1', '2F-4', nan, nan, nan, nan, '1F-1,2F-1', nan, '1F-4', '1F-3', '1F-3', '3F-1', '1F-5', '1F-4', '1F-5', '1F-2', nan, nan, '2F-5', nan, nan, '1F-3', '1F-5', nan, '1F-5', '1F-3', '1F-5', nan, nan, '2F-3', nan, '2F-1,3F-1', nan, '1F-5', nan, nan, nan, '2F-1,3F-3', nan, nan, nan, nan, '2F-4', nan, nan, nan, nan, '1F-1,2F-3', '2F-3', '1F-4', nan, '1F-5', '1F-3', '3F-5', '3F-3', '1F-1,2F-3', '1F-5', '1F-3', nan, '3F-2', nan, '1F-1,2F-1,3F-4', '1F-3', nan, '1F-3', '1F-1', nan, nan, '3F-2', '2F-4', '2F-2', nan, nan, nan, nan, '1F-3', '1F-4', '1F-3', '2F-5', '1F-2', '1F-1,2F-1,3F-3', nan, '3F-1', '1F-1,3F-2', '1F-4', nan, '1F-3', '2F-5', '1F-1,2F-2', '1F-1,2F-2', nan, '1F-2', '1F-3', '1F-1,3F-2', '1F-3', '2F-3', '1F-3', '1F-2', nan, nan, '1F-1', '1F-3', '2F-1,3F-5', '1F-5', nan, '2F-2', '2F-2', nan, '2F-5', '1F-3', '3F-5', '2F-2', nan, '3F-4', '1F-1,3F-4', '1F-5', '2F-1', '1F-1,2F-2', nan, nan, '2F-2', '2F-2', '1F-5', '1F-4', nan, nan, nan, '2F-1,3F-2', '1F-5', '1F-5', nan, '1F-1,2F-2', nan, '2F-5', '2F-4', '1F-4', '2F-5', '1F-4', '2F-3', nan, '1F-4', nan, '1F-1', '3F-3', nan, '2F-3', '1F-3', nan, '1F-1,2F-4', '2F-3', '1F-1,3F-3', '2F-3', '2F-5', '2F-3', '2F-4', '2F-5', '2F-1', '1F-2', '1F-2', '1F-5', '1F-5', '1F-2', '1F-2', '3F-3', '1F-1,2F-1', '1F-4', nan, '1F-4', '3F-2', nan, nan, nan, nan, '1F-2', '3F-3', '1F-1,2F-2', '1F-1,2F-2', nan, nan, nan, '3F-1', nan, nan, '2F-1', '1F-3', '1F-1,2F-3', '1F-4', '3F-2', '1F-2', nan, nan, '2F-3', nan, '1F-1', '1F-1,2F-3', nan, '1F-4', '2F-2', '1F-4', '1F-1,2F-3', '2F-4', nan, nan, nan, '2F-1,3F-5', '2F-5', nan, '1F-1,3F-5', nan, '2F-2', '2F-4', '1F-5', '1F-5', '3F-1', nan, nan, '3F-4', '2F-2', nan, '1F-1,2F-1,3F-4', nan, nan, '1F-2', '1F-1,2F-1,3F-1', '2F-4', nan, '1F-5', '2F-2', '1F-3', nan, '3F-2', '3F-3', nan, '1F-1', '3F-4', '1F-1,3F-1', nan, '3F-5', '3F-3', '1F-3', '1F-4', nan, '1F-3', '2F-1', nan, nan, nan, nan, '3F-2', nan, nan, nan, nan, '1F-2', '1F-3', '1F-2', '1F-1,2F-2', nan, nan, nan, '3F-5', '3F-1', nan, '2F-4', nan, '3F-3', nan, '1F-5', '3F-5', '3F-4', nan, '3F-3', '2F-1,3F-1', nan, '2F-1,3F-3', nan, '1F-1,2F-3', '1F-3', '1F-2', nan, nan, nan, '2F-2', nan, nan, '3F-2', nan, '3F-3', '3F-4', nan, '1F-3', '3F-1', '3F-1', '1F-1,2F-2', nan, '2F-1,3F-2', '2F-2', '1F-5', nan, '1F-5', '1F-3', nan, '1F-2', '2F-2', '2F-2', nan, nan, '1F-4', '1F-1', '1F-5', '1F-1,2F-1,3F-1', '1F-5', nan, '2F-1', nan, '1F-3', '2F-2', '2F-2', nan, nan, '3F-2', nan, '1F-3', nan, nan, '2F-2', '1F-2', nan, '1F-3', '2F-4', '3F-2', nan, '2F-2', nan, nan, nan, nan, '2F-1,3F-1', '1F-1,3F-2', nan, '2F-1,3F-3', '1F-4', nan, '1F-3', '2F-1,3F-3', '1F-5', nan, '2F-1,3F-2', '1F-5', nan, '2F-5', '2F-4', nan, nan, '2F-2', nan, nan, '2F-2', nan, '3F-3', '1F-3', '2F-1,3F-4', '1F-5', '1F-1,2F-1,3F-1', '2F-3', nan, '2F-5', nan, '2F-1', '3F-5', nan, nan, '1F-2', nan, '3F-3', nan, '1F-2', '1F-1,2F-1,3F-4', nan, '2F-5', '1F-3', nan, nan, '1F-3', '2F-5', '3F-2', '3F-4', nan, nan, '1F-1,2F-1', nan, nan, nan, nan, nan, nan, nan, nan, nan, '2F-2', nan, '2F-3', nan, nan, '1F-4', '1F-4', '2F-5', nan, nan, '2F-2', '1F-3', '2F-3', nan, '2F-1', nan, '1F-3', '1F-2', '1F-1', nan, '1F-3', nan, nan, nan, nan, nan, nan, '1F-2', nan, '1F-4', '2F-2', nan, nan, '1F-3', '1F-1,2F-1', '2F-1', nan, '2F-3', nan, '1F-4', nan, '1F-2', '2F-1', '1F-4', '2F-1', nan, '1F-5', nan, '1F-3', '1F-1', '1F-1', nan, nan, nan, nan, '1F-3', nan, '2F-5', nan, nan, nan, nan, '1F-5', nan, '1F-5', nan, nan, nan, '1F-1,2F-1', '2F-1', '1F-1', '1F-1,2F-2', nan, nan, nan, '1F-4', '1F-1,2F-1', '2F-3', '2F-3', '2F-3', '1F-3', '1F-4', '1F-2', nan, nan, '1F-4', nan, '1F-5', '1F-2', '2F-4', nan, '2F-2', nan, '2F-2', '1F-5', '1F-2', nan, '1F-2', '1F-5', '1F-5', '1F-3', '2F-3', '1F-5', nan, '2F-4', '1F-2', '1F-3', '2F-5', '2F-2', '2F-2', nan, '1F-3', nan, '2F-2', '1F-4', nan, nan, '2F-1', nan, nan, nan, nan, '2F-2', '2F-2', nan, '2F-1', nan, '1F-3', '2F-3', nan, nan, '1F-1,2F-3', '1F-4', '2F-3', '1F-5', nan, '2F-1', '1F-3', nan, '2F-2', nan, '1F-3', nan, '1F-5', '1F-3', '1F-1,2F-1', nan, nan, nan, nan, nan, nan, '2F-4', nan, '2F-1', nan, nan, nan, '1F-3', '1F-4', nan, '1F-2', nan, '1F-3', nan, nan, nan, nan, '1F-2', nan, nan, nan, '1F-1', nan, '3F-1', '1F-1,2F-1', nan, nan, nan, nan, nan, '2F-3', nan, '1F-2', nan, nan, nan, nan, nan, nan, '1F-3', nan, nan, '2F-3', '3F-2', '1F-1', '1F-4', nan, '3F-2', nan, '1F-4', nan, '1F-3', '1F-4', '1F-3', nan, '1F-1', '1F-1,2F-3', nan, nan, '1F-2', nan, nan, nan, nan, nan, '3F-2', nan, nan, '1F-5', nan, '1F-4', '3F-2', nan, '1F-3', nan, '3F-2', '1F-3', '1F-3', nan, '2F-1,3F-3', '1F-2', '1F-2', nan, '2F-2', '1F-1,2F-3', nan, nan, '1F-1', '1F-3', '3F-4', nan, nan, '1F-5', nan, '1F-5', nan, nan, nan, nan, '1F-3', nan, nan, '3F-1', nan, '1F-2', '2F-3', nan, nan, '1F-5', '2F-3', '1F-3', '1F-3', '1F-5', '1F-3', '1F-2', nan, '1F-5', nan, '1F-5', '1F-1,3F-2', nan, '3F-2', nan, '1F-3', '1F-3', nan, nan, '1F-5', nan, nan, nan, nan, '1F-5', '1F-5', '2F-3', nan, '3F-1', nan, '3F-3', '1F-4', nan, nan, '2F-2', '3F-3', '1F-5', '1F-5', nan, nan, '3F-1', '3F-2', '1F-5', '1F-3', '1F-3', '1F-5', '2F-4', nan, nan, '2F-5', '1F-5', '1F-4', '2F-3', '1F-5', nan, '1F-5', '1F-5', '1F-3', '1F-3', nan, nan, nan, nan, '1F-4', '1F-2', '1F-4', '1F-1,2F-3', nan, '2F-5', nan, nan, nan, '1F-5', '3F-5', '1F-2', nan, nan, '2F-1,3F-3', nan, nan, nan, '1F-1,2F-3', '2F-2', '1F-4', '1F-3', nan, '3F-3', '1F-1', nan, nan, '2F-2', nan, '1F-4', '2F-1', '1F-5', '2F-2', nan, nan, '3F-5', '1F-5', nan, '1F-4', '1F-3', '1F-1,2F-3', nan, nan, nan, nan, nan, '1F-3', '3F-2', nan, '2F-2', nan, '2F-2', '2F-1', '1F-1,2F-5', '1F-3', nan, '1F-2', '1F-1', '1F-4', nan, nan, '1F-5', '1F-5', '1F-2', '1F-1,2F-1,3F-1', nan, '1F-5', '1F-5', nan, nan, nan, '1F-5', nan, nan, nan, '2F-3', nan, nan, '1F-2', nan, nan, '1F-5', nan, nan, nan, nan, '2F-1,3F-1', '1F-2', '1F-1,2F-4', '1F-5', nan, '1F-1', nan, nan, nan, '3F-2', nan, nan, nan, nan, nan, '1F-3', '2F-5', nan, nan, '1F-4', nan, nan, nan, '1F-1,2F-1', '1F-1,3F-3', '1F-4', '3F-4', nan, '1F-4', nan, nan, nan, nan, '1F-2', '1F-5', nan, '1F-5', nan, '1F-4', nan, nan, nan, '1F-3', '1F-3', nan, nan, '1F-4', '2F-1,3F-5', '1F-4', nan, nan, '1F-4', '1F-1,3F-3', nan, '1F-1', '2F-4', nan, nan, '1F-5', nan, nan, nan, '3F-2', '1F-1,2F-1,3F-1', nan, nan, '2F-1,3F-3', nan, '1F-5', nan, nan, nan, nan, nan, nan, nan, nan, '1F-1', nan, nan, nan, '1F-5', '1F-4', '3F-3', '2F-1', '1F-3', '1F-3', nan, nan, nan, nan, '3F-3', nan, nan, nan, nan, nan, nan, nan, nan, nan, '1F-5', '1F-5', '1F-5', nan, nan, nan, nan, '1F-5', nan, '3F-4', nan, '1F-2', nan, nan, '2F-1', nan, '2F-1', nan, nan, nan, nan, nan, nan, '2F-5', '2F-1', nan, nan, nan, '1F-3', nan, nan, nan, '1F-2', nan, nan, '2F-3', nan, '1F-1,2F-2', '1F-3', '1F-5', '1F-3', '2F-2', '1F-2', '1F-3', '2F-2', '1F-3', '1F-1', nan, nan, '1F-5', '1F-3', nan, '1F-5', nan, '2F-1', '1F-2', '1F-5', '2F-2', '1F-5', nan, nan, nan, '2F-4', '1F-2', '2F-3', '2F-4', nan, nan, nan, '1F-3', nan, nan, nan, nan, nan, nan, nan, '1F-5', nan, '2F-4', nan, '2F-2', '1F-5', '2F-1', '1F-1,2F-2', nan, nan, '1F-5', '1F-4', nan, '1F-5', '1F-3', nan, nan, nan, '2F-3', '1F-3', '1F-1', nan, '2F-2', nan, nan, '2F-1', nan, '1F-1,2F-2', nan, '2F-2', '2F-4', '2F-1', '2F-1', '2F-4', '1F-5', nan, '1F-3', '1F-2', '1F-3', '1F-3', '2F-1', '1F-3', nan, '1F-4', '2F-1', '1F-1,2F-1', nan, nan, nan, '2F-1', '2F-4', '1F-4', nan, '1F-2', '1F-5', '1F-2', '1F-4', '1F-5', '1F-3', nan, '2F-4', nan, '1F-4', '1F-2', '2F-2', nan, nan, '2F-3', '1F-5', '2F-5', nan, '1F-1', nan, '2F-1', nan, '2F-1', '1F-2', '2F-5', '2F-3', '1F-3', '1F-5', nan, '2F-1', '2F-5', '1F-2', nan, '1F-4', '2F-3', nan, nan, nan, nan, nan, nan, nan, nan, '1F-1', '1F-5', '1F-1', '1F-1', nan, nan, nan, nan, nan, nan, nan, '1F-1', '1F-5', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, '1F-3', nan, nan, nan, nan, nan, nan, '1F-2', nan, '1F-1', nan, nan, nan, nan, '1F-5', '1F-3', '1F-4', '1F-5', nan, nan, '1F-3', nan, '1F-2', nan, nan, nan, nan, nan, nan, '1F-4', '1F-3', nan, nan, '1F-1', nan, '1F-4', nan, '1F-1', '1F-2', nan, '1F-1', '1F-5', '1F-5', '1F-3', '1F-3', '1F-2', '1F-5', '1F-3', '1F-5', '1F-3', '1F-1', '1F-1', '1F-1', nan, '1F-1', '1F-5', '1F-4', '1F-5', '1F-1', '1F-5', '1F-2', '1F-3', '1F-1', nan, '1F-5', '1F-1', nan, '1F-3', nan, '1F-5', nan, nan, '1F-4', '1F-5', nan, '1F-1', nan, nan, '1F-4', '1F-4', '1F-3', '1F-3', '1F-5', nan, '1F-4', '1F-4', nan, '1F-2', '1F-1', '1F-1', '1F-5', '1F-1', '1F-2', '1F-3', '1F-5', nan, '1F-3', nan, '1F-1', nan, '1F-1', nan, nan, '1F-5', nan, nan, '1F-5', nan, '1F-5', nan, '1F-3', '1F-1', nan, '1F-2', '1F-2', '1F-1', nan, '1F-2', '1F-1', '1F-5', nan, '1F-3', '1F-5', '1F-2', nan, nan, nan, nan, '1F-1', nan, nan, nan, '1F-5', '1F-4', '1F-5', nan, '1F-1', nan, '1F-1', '1F-2', '1F-2', '1F-1', '1F-3', nan, nan, nan, '1F-3', nan, nan, '1F-4', nan, '1F-2', '1F-5', '1F-2', nan, nan, '1F-5', nan, '1F-1', nan, '1F-5', nan, nan, nan, nan, nan, nan, nan, '1F-1', '1F-1', '1F-1', '1F-1', nan, '1F-2', nan, nan, '1F-4', nan, nan, nan, '1F-1', nan, '1F-5', '1F-5', '1F-4', nan, '1F-4', '1F-1', '1F-5', nan, nan, '1F-1', '1F-4', nan, '1F-4', nan, nan, '1F-2', nan, nan, '1F-1', '1F-1', '1F-2', nan, nan, '1F-2', '1F-3', '1F-4', '1F-5', nan, nan, nan, '1F-2', nan, nan, nan, '1F-2', '1F-5', '1F-5', nan, nan, nan, nan, nan, '1F-1', nan, nan, nan, '1F-1', nan, '1F-3', '1F-1', nan, '1F-1', '1F-1', nan, '1F-1', '1F-1', '1F-1', '1F-4', '1F-1', '1F-1', nan, '1F-5', '1F-2', '1F-1', nan, '1F-1', '1F-1', nan, nan, nan, nan, nan, '1F-2', nan, nan, '1F-1', '1F-3', nan, nan, '1F-3', nan, '1F-1', '1F-5', nan, '1F-4', '1F-1', '1F-4', nan, '1F-1', nan, nan, '1F-4', nan, nan, nan, '1F-5', nan]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 ...]

In [30]:
#Analogia utilizada para realizar la funcion de la siguiente seccion
#Primer final que existe
empanada = "Tres tristes tigres 1F-5 tragan trigo en un trigal"
posicion = empanada.find("1F")
nota = empanada[posicion+3]
print("La nota de primer final es: ", nota)
#Segundo final que no existe
posicion = empanada.find("2F")
if posicion != -1:
 nota = empanada[posicion+3]
 print("La nota de segundo final es: ", nota)
else:
 print("No se encontró nota de segundo final")

La nota de primer final es:  5
No se encontró nota de segundo final

In [31]:

def extractor(vector,comparador):
    salida=np.zeros(len(vector))
    for i in range(len(vector)):
        #Esta funcion busca 
        posicion=vector[i].find(comparador)
        #primero verifica si el valor en el vector original es un NaN, para transcribirlo en el vector de salida
        if vector[i]==nan:
            salida[i]=vector[i]
        
        elif posicion != -1:
            salida[i]=vector[posicion+3]
        else:
            salida[i]=0;
    return salida