In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#Importamos el dataset a utilizar
#Configuramos pandas para visualizar todas las columnas del dataframe
pd.set_option('display.max_columns', None)

#creamos un dataframe a partir de un dataset
df= pd.read_csv("datosConcatenados_completo.csv",sep=",",index_col=False)
df.head()

,Unnamed: 0,danho,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Cod.Curso,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,0,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,N,0,0,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_0
1,1,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,NaN,NaN,es_1
2,2,2012,1,2402,COMBUSTION,INT9MECANI,13,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,NaN,NaN,es_2
3,3,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,NaN,NaN,es_3
4,4,2012,1,2402,COMBUSTION,MEC9-OPT,13,1,2012,1,N,0,11,4,8,0,0,NaN,0.0,1.0,NaN,NaN,es_4

# Eliminacion de Datos Innecesarios
Previamente se demostro que la columna de 'danho'y 'Anho' contienen la misma informacion. Se eliminara una de ellas para eliminar datos redundantes. La columna 'Unnamed: 0' y 'Cod.Curso' tampoco aporta datos que sean de utilidad.

In [3]:
df=df.drop(['Unnamed: 0'],axis=1)
df=df.drop(['danho'],axis=1)
df=df.drop(['Cod.Curso'],axis=1)

In [4]:
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,N,0,0,0,0,0,0,NaN,0.0,1.0,NaN,NaN,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,NaN,NaN,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,NaN,NaN,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,NaN,NaN,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,N,0,11,4,8,0,0,NaN,0.0,1.0,NaN,NaN,es_4

Tambien comprobaremos que columnas contienen datos no disponibles

# Relleno de datos faltantes
Es necesario comprobar que no falten datos en el dataframe. Pero de ser asi, es necesario llenar estos datos faltantes con algun dato auxiliar para poder realizar el preprocesamiento

In [5]:
#Primeramente, verificamos que columnas contienen datos faltantes.
df.isna().sum()/len(df)*100

ciclo            0.00000
Cod.Asign        0.00000
Asignatura       0.00000
Cod.Car.Sec      0.00000
Convocatoria     0.00000
Anho             0.00000
Semestre         0.00000
Aprobado         0.00000
Anho.Firma       0.00000
Primer.Par       0.00000
Segundo.Par      0.00000
AOT              0.00000
Primer.Rec       0.00000
Segundo.Rec      0.00000
Nota.Final      38.21450
Tercer.Par       0.00000
Asis             0.00000
Cuarto.Par      87.36262
4P_60           87.36262
id_anony         0.00000
dtype: float64

Como se puede apreciar, los datos para el 'Cuarto.Par', '4P_60' y 'Nota.Final' estan mayormente incompletas. Para solucionar este problema, se opta por llenar con 0 los datos faltantes.

In [6]:
df.fillna(0,inplace=True)

In [7]:
#Verificamos que ya no quedan datos faltantes
df.isna().sum()/len(df)*100

ciclo           0.0
Cod.Asign       0.0
Asignatura      0.0
Cod.Car.Sec     0.0
Convocatoria    0.0
Anho            0.0
Semestre        0.0
Aprobado        0.0
Anho.Firma      0.0
Primer.Par      0.0
Segundo.Par     0.0
AOT             0.0
Primer.Rec      0.0
Segundo.Rec     0.0
Nota.Final      0.0
Tercer.Par      0.0
Asis            0.0
Cuarto.Par      0.0
4P_60           0.0
id_anony        0.0
dtype: float64

In [8]:
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,N,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,S,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,S,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,N,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

# Preprocesamiento de Datos
Como ya nos encargamos de los datos faltantes. Ahora es necesario procesar ciertos datos tal que la lectura para su uso sea mas accesible para el algoritmo.

Empecemos por lo mas sencillo, si el alumno aprobo o no la materia. Si bien tenemos la columna 'Aprobado' esta columna tiene como datos S y N. Es necesario cambiar esto por algo mas legible para el algoritmo

In [9]:
df["Aprobado"].replace({"S": 1, "N": 0}, inplace=True)
df.head()

,ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,Primer.Par,Segundo.Par,AOT,Primer.Rec,Segundo.Rec,Nota.Final,Tercer.Par,Asis,Cuarto.Par,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

__El 2020__

A inicios del ultimo ciclo del 2019, el COVID-19 llego al Paraguay. Esta enfermedad trajo nuevos desafios al sistema academico de ese entonces. Puesto que todo se realizaba en formato presencial. El pais entro en una cuarentena preventiva estricta, y la facultad cumplio con estas normativas. 

Como este ultimo ciclo del 2019 recien estaba empezando en ese entonces, y se tuvo un receso academico de varios meses. La solucion que se impuso en la facultad fue la de reanudar este ultimo ciclo a partir de la mitad del 2020 en adelante. Junto con esta desicion, se implementaron reglas especiales que solo se aplicaron a este ciclo unico del 2020. Estas regla son:
* Los primeros 3 paciales son sobre 12 puntos cada uno, la suma de los mejores dos examenes equivale a la firma del "1er Parcial"
* El 4to Parcial puede tener el mismo peso que el de un 2do Parcial tradicional o puede tener el mismo peso que un examen recuperatorio. Esto depende de que puntaje es mas elevado. Si la sumatoria del "1er parcial" y el 4to Parcial superan a un examen de 4to Parcial tomado sobre 60, la firma del estudiante es la sumatoria. Caso contrario se toma el puntaje del 4to Parcial sobre 60

Teniendo en cuenta que el 3er y 4to pacial forman parte del proceso para realizar predicciones, no pueden ser obviados.

A continuacion, se realizaran cambios en los nombres de las columnas de datos para facilitar su comprension

In [10]:
#Renombramos las columnas con nombres complicados a otros mas sencillos
df.rename(columns={'ciclo' : 'Ciclo','Primer.Par':'1P','Segundo.Par':'2P','AOT':'Taller','Primer.Rec':'1R'},inplace = True)
df.rename(columns={'Segundo.Rec':'2R','Tercer.Par':'3P','Cuarto.Par':'4P','Asis':'Asistencia'},inplace = True)

df.head()

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony
0,1,2402,COMBUSTION,INT9MECANI,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,COMBUSTION,INT9MECANI,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,COMBUSTION,MEC9-OPT,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

In [11]:
#Ahora verificamos que tipos de datos utiliza cada columna
df.dtypes

Ciclo             int64
Cod.Asign         int64
Asignatura       object
Cod.Car.Sec      object
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
dtype: object

'Cod.Car.Sec' se refiere al plan y la carrera que sigue el alumno en la facultad. Este es un dato relevante. Asi que es necesario discretizarlo para poder utilizar esto como un dato de entrada mas adelante. Tambien es necesario aplicar el mismo procedimiento con 'Asignatura'

In [12]:
#Empecemos con la carrera
#Como Cod.Car.Sec es un object, es necesario asignarle un codigo para que sea procesable

aux1=df['Cod.Car.Sec'] 
aux2=df['Asignatura']

#Creamos un vector de tipo object que contiene las carreras con las que estamos trabajando
carreras=np.unique(df['Cod.Car.Sec'])

#Aqui se categorizan las carreras y se les asigna un numero entero como su codigo
df['Cod.Car.Sec'] = pd.Categorical(df['Cod.Car.Sec'])
df['Cod.Car.Sec'] = df['Cod.Car.Sec'].cat.codes

#Guardamos en un vector los codigos de las carreras
cod_carreras=np.unique(df['Cod.Car.Sec'])

#Visualizamos el nombre de cada carrera y su codigo respectivo
#display(carreras)
#display(cod_carreras)

#Aplicamos el mismo procedimiento para la asignatura
materias=np.unique(df['Asignatura'])
df['Asignatura'] = pd.Categorical(df['Asignatura'])
df['Asignatura'] = df['Asignatura'].cat.codes


cod_materias=np.unique(df['Asignatura'])

#display(materias)
#display(cod_materias)

In [13]:
#A continuacion, creamos dos dataframes para facilitar la identificacion de las carreras y las asignaturas
#Empezamos con el identificador de la carrera
identificador_carrera=pd.DataFrame(data=carreras,index=None,columns=["Carrera"])
identificador_carrera["Codigo"]=cod_carreras

identificador_carrera

       Carrera  Codigo
0   CGF-175-09       0
1   CGF-PLS09        1
2   CGF-PLS13        2
3   CIV-175-09       3
4   CIV-PLS09        4
5   CIV-PLS13        5
6   ECA-175-09       6
7   ECA-PLS09        7
8   ECA-PLS13        8
9   ECA9-OPT         9
10  ELE-175-09      10
11  ELE-PLS09       11
12  ELE-PLS13       12
13  IND-175-09      13
14  IND-PLS09       14
15  IND-PLS13       15
16  INT9-PROYT      16
17  INT9CONSTR      17
18  INT9ELECTR      18
19  INT9G-ECO       19
20  INT9MECANI      20
21  INT9ORTERR      21
22  INT9RNYMA       22
23  INT9SANEHI      23
24  INT9SDIGYT      24
25  INT9TRANSP      25
26  MCT-175-09      26
27  MCT-PLS09       27
28  MCT-PLS13       28
29  MCT9-OPT        29
30  MEC-175-09      30
31  MEC-PLS09       31
32  MEC-PLS13       32
33  MEC9-OPT        33
34  TIVAS           34

In [14]:
#Ahora podemos guardar este dataframe para utilizarlo en los modelos
identificador_carrera.to_csv("identificador_carrera.csv",index=False)

In [15]:
#Ahora, graficamos el identificador de la asignatura
identificador_asignatura=pd.DataFrame(data=materias,index=None,columns=["Asignatura"])
identificador_asignatura["Codigo"]=cod_materias



with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(identificador_asignatura)

                                            Asignatura  Codigo
0               ACONDICIONADOR DE AIRE Y REFRIGERACION       0
1           ACONDICIONAMIENTO DEL AIRE Y REFRIGERACION       1
2                       ACTUADORES Y MAQ. ELECTRICAS 1       2
3                     ACTUADORES Y MAQUINAS ELECTRICAS       3
4                          ADMINISTRACION DE EMPRESAS        4
5                              ADMINISTRACION DE RR HH       5
6                          ADMINISTRACION FINANCIERA         6
7                   AERODINAMICA DE LAS CONSTRUCCIONES       7
8                                    AEROTRIANGULACION       8
9                                   AGUAS SUBTERRANEAS       9
10                  AIRE ACONDICIONADO Y REFRIGERACION      10
11                                    ALGEBRA LINEAL 1      11
12                                    ALGEBRA LINEAL 2      12
13                                          ALGORITMOS      13
14                                        ALGORITMOS 1      14
15                                        ALGORITMOS 2      15
16                                  ANALISIS DE COSTOS      16
17                                ANALISIS DE NEGOCIOS      17
18                                ANALISIS DE SISTEMAS      18
19                   ANALISIS DE SISTEMAS DE POTENCIA       19
20                                             ANTENAS      20
21        APLIC. SIG EN EL ORDENAMIENTO RURAL Y URBANO      21
22                   APLICACION DE MODELOS HIDRAULICOS      22
23               APLICACIONES SIG  EN ESTUDIOS URBANOS      23
24                         ARQUITECTURA IP CONVERGENTE      24
25                                         ASTRONOMIA       25
26                            AUTOMATIZACION Y CONTROL      26
27                                         AUTOMOTORES      27
28                                   AVALUO Y TASACION      28
29                                  AVALUO Y TASACION       29
30                                       BASE DE DATOS      30
31                                  BIOLOGIA AMBIENTAL      31
32                               CABLEADO ESTRUCTURADO      32
33                                           CALCULO 1      33
34                                           CALCULO 2      34
35                                           CALCULO 3      35
36                                           CALCULO 4      36
37                                           CALCULO 5      37
38                         CALIDAD E IMPACTO AMBIENTAL      38
39                 CAMBIO CLIMATICO PARA LA INGENIERIA      39
40                                       CARTOGRAFIA 1      40
41                                       CARTOGRAFIA 2      41
42                       CARTOGRAFIA DIGITAL APLICADA       42
43                                CENTRALES ELECTRICAS      43
44                           CIENCIA DE LOS MATERIALES      44
45              CIENCIA Y TECNOLOGIA DE LOS MATERIALES      45
46                          CIENCIAS DE LOS MATERIALES      46
47                                   CIENCIAS SOCIALES      47
48                                CIRCUITOS ELECTRICOS      48
49                                          COMBUSTION      49
50                                    COMERCIALIZACION      50
51   COMPORTAMIENTO EXPERIMENTAL DE ELEMENTOS DE H° A°      51
52                                         COMPUTACION      52
53                              COMUNICACIONES MOVILES      53
54                              COMUNICACIONES OPTICAS      54
55                                    CONSTRUCCIONES 1      55
56                                    CONSTRUCCIONES 2      56
57                                    CONSTRUCCIONES 3      57
58                          CONSTRUCCIONES SOSTENIBLES      58
59                                        CONTABILIDAD      59
60                             CONTABILIDAD FINANCIERA      60
61                     CONTABILIDAD Y ADM. FINANCIERA       61
62                             CONTABILIDAD Y FINANZAS      62
63                      CONTROL NUMERICO COMPUTARIZADO      63
64                               CONTROLADORES LOGICOS      64
65                                 COSTOS INDUSTRIALES      65
66   CUENCAS HIDROLOGICAS Y EL DESARROLLO TERRITORI...      66
67                           DESARROLLOS INMOBILIARIOS      67
68                                     DIBUJO MECANICO      68
69                                      DIBUJO TECNICO      69
70                                            DINAMICA      70
71                  DINAMICA DE MAQUINAS Y VIBRACIONES      71
72   DINAMICA Y CONTROL DE SISTEMAS ELECTRICO DE PO...      72
73                               DISEÑO DE GEODATABASE      73
74                      DISEÑO DE INST. INDUSTRIALES 1      74
75                      DISEÑO DE INST. INDUSTRIALES 2      75
76             DISEÑO DE INSTALACIONES P/ INDUSTRIAS 1      76
77            DISEÑO DE INSTALACIONES P/ INSDUSTRIAS 2      77
78                                   DISEÑO DE MAQUINA      78
79                           DISEÑO DE SIST. DE MANUF.      79
80                   DISEÑO DE SISTEMAS DE MANUFACTURA      80
81                                  DISEÑO ESTRUCTURAL      81
82                    DISEÑO ESTRUCTURAL DE PAVIMENTOS      82
83                              DISEÑO GEOMETRICO VIAL      83
84                               DISEÑO LOGICO DIGITAL      84
85                             DISEÑO LOGICO DIGITAL 1      85
86                             DISEÑO LOGICO DIGITAL 2      86
87                   DISEÑO Y COMPOS. DE MAPAS Y ATLAS      87
88            DISEÑO Y DESARROLLO DE PROYECTOS URBANOS      88
89          DISEÑO Y DESARROLLO DE PROYECTOS URBANOS 2      89
90             DISEÑO Y PUBLICACION DE MAPAS EN LA WEB      90
91                 DISTRIBUCION DE  ENERGIA  ELECTRICA      91
92                   DISTRIBUCION DE ENERGIA ELECTRICA      92
93                                            DOMOTICA      93
94                                            ECONOMIA      94
95                 ECONOMIA  Y  EVALUACION DE PROYECTO      95
96                                  ECONOMIA AMBIENTAL      96
97                                   ECONOMIA POLITICA      97
98                                  ECONOMIA POLITICA       98
99                   ECONOMIA Y EVALUACION DE PROYECTO      99
100                                         EDAFOLOGIA     100
101                                        EDAFOLOGIA      101
102                              EFICIENCIA ENERGETICA     102
103                ELECTRICIDAD Y CIRCUITOS ELECTRICOS     103
104                                  ELECTROMAGNETISMO     104
105                                ELECTROMAGNETISMO 1     105
106                                ELECTROMAGNETISMO 2     106
107                                      ELECTRONICA 1     107
108                                      ELECTRONICA 2     108
109                                      ELECTRONICA 3     109
110                 ELECTRONICA APLICADA EN POTENCIAS      110
111                                 ELECTRONICA BASICA     111
112                      ELECTRONICA BASICA INDUSTRIAL     112
113                             ELECTRONICA INDUSTRIAL     113
114                                      ELECTROTECNIA     114
115                                    ELECTROTECNIA 1     115
116                                    ELECTROTECNIA 2     116
117           ELECTROTECNIA E INSTALACIONES ELECTRICAS     117
118          ELECTROTECNIA E INSTALACIONES ELECTRICAS      118
119                              ELEMENTOS DE MAQUINAS     119
120                            ENERGIA SOLAR Y BIOMASA     120
121                                           ESTATICA     121
122              ESTRATEGIAS Y TECNICAS DE NEGOCIACION     122
123                               ESTRUCT. MET. ESPEC.     123
124                       ESTRUCTURA DE MADERA Y METAL     124
125                   ESTRUCTURA METALICA Y DE MADERAS     125
126                                      ESTRUCTURAS 1     126
127                                      ESTRUCTURAS 2     127
128                                      ESTRUCTURAS 3     128
129                              ESTRUCTURAS METALICAS     129
130                                ESTUDIOS DE SUELOS      130
131                            EVALUACION DE PROYECTOS     131
132                                  EVALUACION SOCIAL     132
133                     EVALUACION Y GESTION AMBIENTAL     133
134                    EVALUACION Y GESTION AMBIENTAL      134
135                            FENOMENOS DE TRANSPORTE     135
136                                           FINANZAS     136
137                                           FISICA 1     137
138                                           FISICA 2     138
139                                           FISICA 3     139
140                                           FISICA 4     140
141                          FISICA DE SEMICONDUCTORES     141
142                                FISICA GRAVIMETRICA     142
143                               FISICA GRAVIMETRICA      143
144                        FORM. Y EVAL. DE PROYECTOS      144
145                    FORM. Y EVALUACION DE PROYECTOS     145
146               FORMULACION Y EVALUACION DE PROYECTO     146
147                 FORMULACION Y GESTION DE PROYECTOS     147
148                                    FOTOGRAMETRIA 1     148
149                                    FOTOGRAMETRIA 2     149
150                                   FOTOGRAMETRIA 2      150
151                              FOTOGRAMETRIA DIGITAL     151
152                                    FOTOGRAMETRIA I     152
153                                  FOTONICA APLICADA     153
154                    FUNDAMENTO DE LA MECANICA NAVAL     154
155              FUNDAMENTOS DE ELECTRONICA INDUSTRIAL     155
156                        FUNDAMENTOS DE MEDIO DE RED     156
157                      FUNDAMENTOS DE PLANTA EXTERNA     157
158  FUNDAMENTOS MATEMATICOS PARA LA CIENCIAS GEOGR...     158
159                                GEODESIA GEOMETRICA     159
160                               GEODESIA GEOMETRICA      160
161                              GEODESIA GRAVIMETRICA     161
162                             GEODESIA GRAVIMETRICA      162
163                                 GEODESIA SATELITAL     163
164                                   GEOGRAFIA HUMANA     164
165                                  GEOGRAFIA HUMANA      165
166                                GEOGRAFIA TURISTICA     166
167                              GEOLOGIA DEL PARAGUAY     167
168                                   GEOLOGIA GENERAL     168
169                                  GEOLOGIA GENERAL      169
170                                GEOMETRIA ANALITICA     170
171                              GEOMETRIA DESCRIPTIVA     171
172                                      GEOMORFOLOGIA     172
173                                     GEOMORFOLOGIA      173
174                                        GEOTECNIA 1     174
175                                        GEOTECNIA 2     175
176               GEST. DE CALIDAD E IMPACTO AMBIENTAL     176
177                                 GESTION DE CALIDAD     177
178                                GESTION DE CALIDAD      178
179             GESTION DE LA CALIDAD Y MEDIO AMBIENTE     179
180                               GESTION DE PROYECTOS     180
181               GESTION DE SALUD Y SEGURIDAD INDUST.     181
182                                GESTION EMPRESARIAL     182
183                       GESTION INTEGRAL DE RESIDUOS     183
184       GESTION Y CONSERVACION DE RECURSOS NATURALES     184
185                                       HIDRAULICA 1     185
186                                       HIDRAULICA 2     186
187                                      HIDROGEOLOGIA     187
188                                       HIDROLOGIA 2     188
189                  HIDROLOGIA GENERAL  E HIDRAULICA      189
190                    HIDROLOGIA GENERAL E HIDRAULICA     190
191                                      HIDROTECNIA 1     191
192                                      HIDROTECNIA 2     192
193                     HIGIENE Y SEGURIDAD INDUSTRIAL     193
194                                  HORMIGON ARMADO 1     194
195                                  HORMIGON ARMADO 2     195
196                                HORMIGON PRETENSADO     196
197                  IMPACTO AMBIENTAL EN OBRAS VIALES     197
198                                        INFORMATICA     198
199                                      INFORMATICA 2     199
200                INFRAESTRUCTURA DE DATOS ESPECIALES     200
201        INGENIERIA DE CONFIABILIDAD Y MANTENIMIENTO     201
202                        INGENIERIA DE MANTENIMIENTO     202
203                             INGENIERIA DEL TRAFICO     203
204                               INGENIERIA ECONOMICA     204
205                                     INGLES TECNICO     205
206                                INMOTICA Y DOMOTICA     206
207                        INNOVACION Y EMPRENDIMIENTO     207
208           INSTALACION Y EQUIPAMIENTO DE EDIFICIOS      208
209                         INSTALACIONES  ELECTRICAS      209
210                        INSTALACIONES  INDUSTRIALES     210
211                           INSTALACIONES ELECTRICAS     211
212                INSTALACIONES ELECTRICAS ESPECIALES     212
213                         INSTALACIONES INDUSTRIALES     213
214               INSTALACIONES Y EQUIPOS DE EDIFICIOS     214
215                       INSTR. PARA CONTROL Y AUTOM.     215
216                        INSTRUMENTACION PARA TELEC.     216
217            INSTRUMENTACION PARA TELECOMUNICACIONES     217
218                   INSTRUMENTACION Y AUTOMATIZACION     218
219            INSTRUMENTACION Y MEDICIONES ELECTRICAS     219
220                   INSTRUMENTACIÓN Y AUTOMATIZACION     220
221         INSTRUMENTOS PARA CONTROL Y AUTOMATIZACION     221
222                      INT. A LA PROGRAMACION DE CNC     222
223                            INTELIGENCIA ARTIFICIAL     223
224                   INTERPRETACION DE IMAGENES RADAR     224
225  INTR AL DESARROLLO TERRITORIAL- MANEJO DE CONS...     225
226  INTR. AL PROYECTO Y DISEÑO DE TORRES DE TELECO...     226
227                      INTROD. A LA INGENIERIA NAVAL     227
228                   INTRODUCCION  A LA INVESTIGACION     228
229                  INTRODUCCION A ELECTRONICA MEDICA     229
230                INTRODUCCION A LA CIENCIA AMBIENTAL     230
231               INTRODUCCION A LA ELECTRONICA MEDICA     231
232                   INTRODUCCION A LA ENERGIA EOLICA     232
233             INTRODUCCION A LA ENERGIA FOTOVOLTAICA     233
234       INTRODUCCION A LA FISICA ATOMICA Y MOLECULAR     234
235               INTRODUCCION A LA GESTION DE ACTIVOS     235
236                    INTRODUCCION A LA INVESTIGACION     236
237                          INTRODUCCION A LA MINERIA     237
238                       INTRODUCCION A LA SIMULACION     238
239          INTRODUCCION AL ORDENAMIENTO TERRITORIAL      239
240                           INVEST. DE OPERACIONES 2     240
241                           INVEST. DE OPERACIONES 3     241
242                     INVESTIGACION DE OPERACIONES 1     242
243                     INVESTIGACION DE OPERACIONES 2     243
244                     INVESTIGACION DE OPERACIONES 3     244
245                            INVESTIGACION OPERATIVA     245
246                               LABORATORIO DE REDES     246
247                             LABORATORIO MECANICO 1     247
248                             LABORATORIO MECANICO 2     248
249                             LABORATORIO MECANICO 3     249
250                                   LABORATORIO VIAL     250
251                                    LEAN PRODUCTION     251
252                                        LEGISLACION     252
253                           LENGUAJE DE PROGRAMACION     253
254                    LENGUAJE DE PROGRAMACION VISUAL     254
255      LEVANT. REG., CATASTRALES E HIDROTOPOGRAFICOS     255
256            LEVANTAMIENTO REGIONALES Y CATASTRALES      256
257                                          LOGISTICA     257
258                         LT PARA TELECOMUNICACIONES     258
259                           MANTENIMIENTO DE CAMINOS     259
260                           MANTENIMIENTO INDUSTRIAL     260
261                             MANTENIMIENTO MECANICO     261
262                            MAQUINAS  ELECTRICAS  1     262
263                              MAQUINAS  TERMICAS  2     263
264                                  MAQUINAS DE FLUJO     264
265                                 MAQUINAS DE FLUJO      265
266                                MAQUINAS ELECTRICAS     266
267                              MAQUINAS ELECTRICAS 1     267
268                              MAQUINAS ELECTRICAS 2     268
269                               MAQUINAS HIDRAULICAS     269
270                               MAQUINAS TERMICAS  1     270
271                                MAQUINAS TERMICAS 1     271
272                                MAQUINAS TERMICAS 2     272
273            MAQUINAS Y EQUIPOS PARA LA CONSTRUCCION     273
274                                       MATERIALES 1     274
275                                       MATERIALES 2     275
276                           MATERIALES DE INGENIERIA     276
277                       MATERIALES DE OBRAS CIVILES      277
278                      MATERIALES DE OBRAS CIVILES 1     278
279                      MATERIALES DE OBRAS CIVILES 2     279
280                                MECANICA DE FLUIDOS     280
281                     MECANICA DE FLUIDOS AVANZADOS      281
282                           MECANICA DE MATERIALES 1     282
283                           MECANICA DE MATERIALES 2     283
284                                MECANICA DE SOLIDOS     284
285                           MECANICA DE SUELO Y ROCA     285
286                                         MECANISMOS     286
287                            MECANIZADO CONVENCIONAL     287
288                         MEDICION E INSTRUMENTACION     288
289                       MEDICIONES E INSTRUMENTACION     289
290                                MERCADOS ELECTRICOS     290
291                        METEOROLOGIA Y CLIMATOLOGIA     291
292                       METODOLOGIA DE INVESTIGACION     292
293                   METODOLOGIA DE LA INVESTIGACION      293
294                                  METODOS NUMERICOS     294
295                                         METROLOGIA     295
296                                 MICROCONTROLADORES     296
297                                   MICROELECTRONICA     297
298                                         MICROONDAS     298
299  MODELACION COMPUTACIONAL DE ESTRUCTURAS-METODO...     299
300                                MONITOREO AMBIENTAL     300
301                       MOTORES Y COMPONENTES AUTOM.     301
302                                NOCIONES DE DERECHO     302
303                                    OBRAS FLUVIALES     303
304                                   OBRAS FLUVIALES      304
305                           OPERACIONES INDUSTRIALES     305
306                           ORGANIZACION DE EMPRESAS     306
307                         ORGANIZACION DE EMPRESAS 1     307
308                         ORGANIZACION DE EMPRESAS 2     308
309                            ORGANIZACION INDUSTRIAL     309
310    ORGANIZACION INDUSTRIAL Y SEGURIDAD DEL TRABAJO     310
311                                           PASANTIA     311
312                                          PASANTIAS     312
313                                         PASANTIAS      313
314          PATOLOGIA Y TERAPIA DE LAS CONSTRUCCIONES     314
315               PLANEAMIENTO Y CONTROL DE PRODUCCION     315

In [16]:
#Ahora podemos guardar este dataframe para utilizarlo en los modelos
identificador_asignatura.to_csv("identificador_asignatura.csv",index=False)

In [17]:
#Visualizamos los tipos de datos con los que trabajamos ahora
display(df.dtypes)
#Visualizamos el modelo
df.head()

Ciclo             int64
Cod.Asign         int64
Asignatura        int16
Cod.Car.Sec        int8
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
dtype: object

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony
0,1,2402,49,20,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0
1,1,2402,49,33,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1
2,1,2402,49,20,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2
3,1,2402,49,33,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3
4,1,2402,49,33,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4

Tambien vamos a anotar si el alumno es recursante. Eso se puede saber a partir de la columna "Anho.Firma"

In [18]:
#Creamos un vector que confirma si un alumno es recursante
recursante=df['Anho.Firma']!=0
recursante
#Pasamos los datos booleanos del vector a formato entero
recursante=recursante.replace([True,False],[1,0])
#Este dato sera anhadido al dataframe mas adelante

Ahora es necesario procesar los datos que se encuentran en la nota final. Actualmente, la columna 'Nota.Final' es un objeto. Se optara por obtener el puntaje que el alumno adquirio en cada examen final y finalmente se anhadira una columna con el puntaje final adquirido en esa materia

In [19]:
#Primero comprobamos que tipos de datos hay en la columnas de 'Nota.Final'. Con esta informacion, sera mas sencillo definir
#el algoritmo para extraer las notas finales
notas=np.unique(df['Nota.Final'].tolist())
print(notas)

['0' '1F-1' '1F-1,2F-1' '1F-1,2F-1,3F-1' '1F-1,2F-1,3F-2' '1F-1,2F-1,3F-3'
 '1F-1,2F-1,3F-4' '1F-1,2F-1,3F-5' '1F-1,2F-1,ME-3' '1F-1,2F-2'
 '1F-1,2F-3' '1F-1,2F-4' '1F-1,2F-5' '1F-1,2F-C-2' '1F-1,2F-C-4'
 '1F-1,3F-1' '1F-1,3F-1,2F-1' '1F-1,3F-2' '1F-1,3F-2,2F-1' '1F-1,3F-3'
 '1F-1,3F-3,2F-1' '1F-1,3F-4' '1F-1,3F-4,2F-1' '1F-1,3F-5'
 '1F-1,3F-5,2F-1' '1F-1,3F-C-1' '1F-1,3F-C-3' '1F-1,ME-3' '1F-2' '1F-3'
 '1F-4' '1F-5' '1F-5F' '1F-C-1' '1F-C-1,2F-C-1' '1F-C-1,2F-C-1,3F-C-1'
 '1F-C-1,2F-C-1,3F-C-2' '1F-C-1,2F-C-1,3F-C-3' '1F-C-1,2F-C-1,3F-C-4'
 '1F-C-1,2F-C-1,3F-C-5' '1F-C-1,2F-C-2' '1F-C-1,2F-C-3' '1F-C-1,2F-C-4'
 '1F-C-1,2F-C-5' '1F-C-1,3F-C-1' '1F-C-1,3F-C-1,2F-C-1' '1F-C-1,3F-C-2'
 '1F-C-1,3F-C-2,2F-C-1' '1F-C-1,3F-C-3' '1F-C-1,3F-C-3,2F-C-1'
 '1F-C-1,3F-C-4' '1F-C-1,3F-C-4,2F-C-1' '1F-C-1,3F-C-5' '1F-C-2' '1F-C-3'
 '1F-C-4' '1F-C-5' '1F-C-5F' '1F-D-1,2F-2' '1F-D-1,2F-C-3' '1F-D-1,2F-C-4'
 '1F-D-1,3F-1' '1F-D-2' '1F-D-4' '1F-D-5' '2F-1' '2F-1,1F-1'
 '2F-1,1F-1,3F-1' '2F-1,1F-1,3F-2' '2F-1,1F-1,3F-3' '2F-1,1F-1,3F-4'
 '2F-1,1F-1,3F-5' '2F-1,3F-1' '2F-1,3F-2' '2F-1,3F-3' '2F-1,3F-3,1F-1'
 '2F-1,3F-4' '2F-1,3F-5' '2F-1,3F-C-1' '2F-2' '2F-2,1F-1' '2F-3'
 '2F-3,1F-1' '2F-4' '2F-4,1F-1' '2F-5' '2F-5,1F-1' '2F-5F' '2F-C-1'
 '2F-C-1,1F-C-1' '2F-C-1,1F-C-1,3F-C-1' '2F-C-1,1F-C-1,3F-C-2'
 '2F-C-1,1F-C-1,3F-C-3' '2F-C-1,1F-C-1,3F-C-4' '2F-C-1,3F-C-1'
 '2F-C-1,3F-C-2' '2F-C-1,3F-C-3' '2F-C-1,3F-C-4' '2F-C-1,3F-C-5' '2F-C-2'
 '2F-C-2,1F-C-1' '2F-C-3' '2F-C-3,1F-C-1' '2F-C-4' '2F-C-4,1F-C-1'
 '2F-C-5' '2F-C-5,1F-C-1' '3F-1' '3F-1,1F-1' '3F-1,1F-1,2F-1' '3F-1,2F-1'
 '3F-2' '3F-2,1F-1' '3F-2,1F-1,2F-1' '3F-2,2F-1' '3F-2,2F-1,1F-1' '3F-3'
 '3F-3,1F-1' '3F-3,1F-1,2F-1' '3F-3,2F-1' '3F-3,2F-1,1F-1' '3F-4'
 '3F-4,1F-1' '3F-4,1F-1,2F-1' '3F-4,2F-1' '3F-5' '3F-5,1F-1' '3F-5,2F-1'
 '3F-5F' '3F-C-1' '3F-C-1,1F-C-1' '3F-C-1,1F-C-1,2F-C-1' '3F-C-1,2F-C-1'
 '3F-C-2' '3F-C-2,1F-C-1' '3F-C-2,1F-C-1,2F-C-1' '3F-C-2,2F-C-1'
 '3F-C-2,2F-C-1,1F-C-1' '3F-C-3' '3F-C-3,1F-C-1' '3F-C-3,2F-C-1' '3F-C-4'
 '3F-C-4,1F-C-1' '3F-C-4,2F-C-1' '3F-C-5' '3F-C-5,2F-C-1' 'ME-2' 'ME-5']

In [20]:
#Aqui definimos la funcion que separara los datos
primerfinal=[]
segundofinal=[]
tercerfinal=[]

#Esta funcion identifica si el alumno rindio el primer, segundo o tercer final teniendo en cuenta que los finales rendidos se
#representan con 1F,2F o 3F

def separar(lista):
    global primerfinal
    global segundofinal
    global tercerfinal
    for nota in lista:
        if nota==0:
            primerfinal.append(0)
            segundofinal.append(0)
            tercerfinal.append(0)
        else:
            if '1F' in nota:
                n=nota.find('1F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    primerfinal.append(int(nota[n+5]))
                else:
                    primerfinal.append(int(nota[n+3]))
            else: 
                primerfinal.append(0)
                
            if '2F' in nota:
                n=nota.find('2F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    segundofinal.append(int(nota[n+5]))
                else:
                    segundofinal.append(int(nota[n+3]))
            else: 
                segundofinal.append(0)
            
            if '3F' in nota:
                n=nota.find('3F')
                if nota[n+3]=='C' or nota[n+3]=='D':
                    tercerfinal.append(int(nota[n+5]))
                else:
                    tercerfinal.append(int(nota[n+3]))
            else: 
                tercerfinal.append(0)

def maximo(a,b,c):
    """
    Esta funcion obtiene la nota mas alta obtenida por el alumno durante los finales. Esta funcion se 
    utiliza para obtener la nota final
    """
    salida=np.zeros(len(a))
    for i in range(len(a)):
        if a[i]>=b[i] and a[i]>=c[i]:
            salida[i]=int(a[i])
        elif b[i]>=c[i]:
            salida[i]=int(b[i])
        else:
            salida[i]=int(c[i])
    return salida.astype(np.int64)

#Cargamos el contenido de 'Nota.Final' en una lista, para asi introducir la lista en la funcion
listaNotas=df["Nota.Final"].tolist()
separar(listaNotas)

#Creamos nuevas columnas en el df y le cargamos los vectores con los datos
df['1F']=primerfinal
df['2F']=segundofinal
df['3F']=tercerfinal

#Hallamos la nota final y la cargamos en una nueva columna en el df
nota_final=maximo(primerfinal,segundofinal,tercerfinal)
df['Nota_Final']=nota_final

df.head()

,Ciclo,Cod.Asign,Asignatura,Cod.Car.Sec,Convocatoria,Anho,Semestre,Aprobado,Anho.Firma,1P,2P,Taller,1R,2R,Nota.Final,3P,Asistencia,4P,4P_60,id_anony,1F,2F,3F,Nota_Final
0,1,2402,49,20,1,2012,1,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,es_0,0,0,0,0
1,1,2402,49,33,1,2012,1,1,2012,11,14,8,0,0,1F-5,0.0,1.0,0.0,0.0,es_1,5,0,0,5
2,1,2402,49,20,1,2012,1,1,2012,24,23,9,0,0,1F-5,0.0,1.0,0.0,0.0,es_2,5,0,0,5
3,1,2402,49,33,1,2012,1,1,2012,11,14,8,0,0,"1F-1,2F-2",0.0,1.0,0.0,0.0,es_3,1,2,0,2
4,1,2402,49,33,1,2012,1,0,0,11,4,8,0,0,0,0.0,1.0,0.0,0.0,es_4,0,0,0,0

In [21]:
#Comprobamos nuevamente el tipo de datos en el dataframe
df.dtypes

Ciclo             int64
Cod.Asign         int64
Asignatura        int16
Cod.Car.Sec        int8
Convocatoria      int64
Anho              int64
Semestre          int64
Aprobado          int64
Anho.Firma        int64
1P                int64
2P                int64
Taller            int64
1R                int64
2R                int64
Nota.Final       object
3P              float64
Asistencia      float64
4P              float64
4P_60           float64
id_anony         object
1F                int64
2F                int64
3F                int64
Nota_Final        int64
dtype: object

Teniendo en cuenta que ya obtuvimos los puntajes de cada final y los separamos, discretizamos para su uso a los datos que pueden ser relevantes para el analisis, y convertimos los datos a un valor legible por el algoritmo. Lo que queda por hacer es eliminar las columnas a las cuales les extrajimos los datos y ya no seran relevantes para nuestro analisis. Tambien reordenamos las columnas para facilitar la lectura de los datos

In [22]:
#Primero eliminamos las columnas que ya no vamos a utilizar
df.drop(['Nota.Final', 'Convocatoria'],axis=1)

df.rename(columns={'Asignatura':'Asignatura Codificada', 'Cod.Car.Sec':'Cod.Car.Sec Codificado'},inplace = True)


df['Cod.Car.Sec']=aux1
df['Asignatura']=aux2

#Ahora reordenamos las columnas de nuestro df
df=df[['id_anony','Anho','Ciclo','Cod.Asign','Asignatura','Asignatura Codificada','Semestre','Cod.Car.Sec','Cod.Car.Sec Codificado','Anho.Firma','1P','2P','3P','4P','Taller','Asistencia','4P_60','1R','2R','1F','2F','3F','Nota_Final','Aprobado']]

#Finalmente, anhadimos la columna que indica si el alumno recurso o no la materia
df.insert(10,"Recursante",recursante,True)

In [23]:
df

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,es_0,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
1,es_1,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,5,0,0,5,1
2,es_2,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,2012,1,24,23,0.0,0.0,9,1.0,0.0,0,0,5,0,0,5,1
3,es_3,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,1,2,0,2,1
4,es_4,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,0,0,11,4,0.0,0.0,8,1.0,0.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221916,es_4501,2021,1,5746,PROCESOS DE FABRICACION,336,1,MCT9-OPT,29,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
221917,es_3417,2021,1,5746,PROCESOS DE FABRICACION,336,1,MCT9-OPT,29,2021,1,17,26,0.0,0.0,10,1.0,0.0,0,0,0,0,0,0,0
221918,es_3784,2021,1,5746,PROCESOS DE FABRICACION,336,1,MCT9-OPT,29,2021,1,19,26,0.0,0.0,10,1.0,0.0,0,0,5,0,0,5,1
221919,es_4309,2021,1,5746,PROCESOS DE FABRICACION,336,1,MCT9-OPT,29,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
221920,es_3891,2021,1,5746,PROCESOS DE FABRICACION,336,1,MCT9-OPT,29,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0

Como los resultados de cada estudiante estan mezclados con los otros, ordenamos el dataframe de acuerdo al ID del estudiante

In [24]:
df.sort_values("id_anony",ascending=True)

df.head()

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,es_0,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,0,0,0,0,0.0,0.0,0,1.0,0.0,0,0,0,0,0,0,0
1,es_1,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,5,0,0,5,1
2,es_2,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,2012,1,24,23,0.0,0.0,9,1.0,0.0,0,0,5,0,0,5,1
3,es_3,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0.0,0.0,8,1.0,0.0,0,0,1,2,0,2,1
4,es_4,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,0,0,11,4,0.0,0.0,8,1.0,0.0,0,0,0,0,0,0,0

In [25]:
#Ahora modificamos el 'id_anony' por una lista de enteros, pues eso sera mas amigable para realizar procesamientos mas adelante
df["id_anony"].astype(str)
alumnos=(df["id_anony"])

alumnos= [s.replace("es_", "") for s in alumnos]

df["id_anony"]=alumnos

df["id_anony"]=df["id_anony"].astype(int)

#Tambien modificamos a tipo entero los flotantes innecesarios
df["3P"]=df["3P"].astype(int)
df["4P"]=df["4P"].astype(int)
df["Asistencia"]=df["Asistencia"].astype(int)
df["4P_60"]=df["4P_60"].astype(int)

#Ademas, se cambiaran los objetos por strings
df["Asignatura"]=df["Asignatura"].astype(str)
df["Cod.Car.Sec"]=df["Cod.Car.Sec"].astype(str)
print(df.dtypes)

id_anony                   int32
Anho                       int64
Ciclo                      int64
Cod.Asign                  int64
Asignatura                object
Asignatura Codificada      int16
Semestre                   int64
Cod.Car.Sec               object
Cod.Car.Sec Codificado      int8
Anho.Firma                 int64
Recursante                 int64
1P                         int64
2P                         int64
3P                         int32
4P                         int32
Taller                     int64
Asistencia                 int32
4P_60                      int32
1R                         int64
2R                         int64
1F                         int64
2F                         int64
3F                         int64
Nota_Final                 int64
Aprobado                   int64
dtype: object

In [26]:
df.head()

,id_anony,Anho,Ciclo,Cod.Asign,Asignatura,Asignatura Codificada,Semestre,Cod.Car.Sec,Cod.Car.Sec Codificado,Anho.Firma,Recursante,1P,2P,3P,4P,Taller,Asistencia,4P_60,1R,2R,1F,2F,3F,Nota_Final,Aprobado
0,0,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,1,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0,0,8,1,0,0,0,5,0,0,5,1
2,2,2012,1,2402,COMBUSTION,49,1,INT9MECANI,20,2012,1,24,23,0,0,9,1,0,0,0,5,0,0,5,1
3,3,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,2012,1,11,14,0,0,8,1,0,0,0,1,2,0,2,1
4,4,2012,1,2402,COMBUSTION,49,1,MEC9-OPT,33,0,0,11,4,0,0,8,1,0,0,0,0,0,0,0,0

Una vez finalizado el preprocesamiento, podemos crear un nuevo dataset con las modificaciones realizadas

In [27]:
df.shape

(221921, 25)

In [28]:
#Creacion de un nuevo dataset con el dataframe final
df.to_csv("Filtrado_final.csv",index=False)